### ISSUE TITLE
Terraform Infrastructure Modules

### ISSUE THREAD

**Issue by Klaas-** [sap-linuxlab/sap-linuxlab.github.io#1]
Hi,
I'd be interested to look at and work with terraform modules to deploy infrastructure, I see that you have already made references  to terraform.sap_infrastructure but it doesn't seem to be public yet. @sean-freeman is listed as maintainer. 

Greetings
Klaas

**Comment by rhmk** [comment]
HI Klaas, thanks for volunteering.  IBM (Sean) will offer it pretty soon. Keep watching

**Comment by sean-freeman** [comment]
@Klaas- Will provide your user with early access to the code before the initial release, happy to do so as I'm looking for feedback.

The initial release contains a baseline of common scenarios (e.g. System Copy) seen at customers worldwide and various Infrastructure Platforms (e.g. MS Azure, AWS, IBM Cloud, IBM Power). It will not initially include HA/DR as a scenario.

It's important to first get the baseline modular code working in the right way with the right code structure, then testing and feedback; thereafter expanding the scope with the guidance of many in the community.

For now will keep issue open as a placeholder.

**Comment by sean-freeman** [comment]
Closing this placeholder issue, @Klaas- has been most helpful
